# Generated by Django 5.1.3 on 2024-12-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hagapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaldata',
            name='signal_column',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='signaldata',
            name='threshold',
            field=models.FloatField(default=0.5),
        ),
    ]
